### ISSUE TITLE
Where do gene symbols come from for human ensembl genes?

### ISSUE THREAD

**Issue by dhimmel** [cogent3/ensembldb3#7]
I am trying to figure out where ensembl stores the symbol for a gene in its MySQL database ([schema](https://uswest.ensembl.org/info/docs/api/core/core_schema.html)). Forgive me for opening an issue here. My excuse is that:

- I don't find email lists very effective for technical discussion or discoverability, so I haven't yet tried the [`dev@ensembl.org` mailing list](http://useast.ensembl.org/info/about/contact/mailing.html)
- The official REST API does provide a display_name field, e.g. `display_name: BRCA2` for https://rest.ensembl.org/lookup/id/ENSG00000139618. But I want to know how this is retrieved from the MySQL database and prefer reading Python to Perl.

From [the ensembldb3 docs](https://github.com/cogent3/ensembldb3/blob/894fcc0f13ed3bd250a04d206d37197d58f67d01/doc/genome.rst#by-ensembl-stable-id):

```python
>>> gene = human.get_gene_by_stableid(stableid='ENSG00000139618')
>>> print(gene)
Gene(species='Homo sapiens'; biotype='protein_coding'; description='BRCA2, DNA repair...'; stableid='ENSG00000139618'; status='KNOWN'; symbol='BRCA2')
```

Note `symbol='BRCA2'`. Now I'd like to figure out where in the database this is coming from.

**Comment by dhimmel** [comment]
I created the following query that gets the symbol via `gene_attrib.value` when `attrib_type.code = "name"`

```sql
SELECT
  gene.stable_id AS ensembl_gene_id,
  gene.version AS ensembl_gene_version,
  gene_attrib_symbol.gene_symbol AS gene_symbol
FROM gene
LEFT JOIN (
  SELECT gene_attrib.gene_id, gene_attrib.value AS gene_symbol
  FROM gene_attrib
  LEFT JOIN attrib_type ON gene_attrib.attrib_type_id = attrib_type.attrib_type_id
  WHERE attrib_type.code = "name"
  -- in case there is ever multiple symbols per gene, filter to one 
  GROUP BY gene_attrib.gene_id
) AS gene_attrib_symbol
  ON gene_attrib_symbol.gene_id = gene.gene_id
-- all genes were current when query was written, ensure this is always the case
WHERE gene.is_current
ORDER BY stable_id
LIMIT 10
```

And ran the query against the public endpoint with the sqlalchemy connection URL of `mysql+mysqlconnector://anonymous@ensembldb.ensembl.org/homo_sapiens_core_102_38`.

However, if we add an additional filter for `AND gene_attrib_symbol.gene_symbol IS NULL`, we see  many ensembl gene IDs without a symbol using this method. For example, ENSG00000170152. However, https://rest.ensembl.org/lookup/id/ENSG00000170152 returns:

```
display_name: AL391987.1
```

**Comment by dhimmel** [comment]
From skimming the source:

https://github.com/cogent3/ensembldb3/blob/894fcc0f13ed3bd250a04d206d37197d58f67d01/ensembldb3/genome.py#L329-L330

Leading me to think symbols are coming from the [`xref.display_label`](https://useast.ensembl.org/info/docs/api/core/core_schema.html#xref) table / column.

**Comment by dhimmel** [comment]
I think I finally cracked it, thanks mostly to this [biostars answer](https://www.biostars.org/p/14367/#83094) by Giulietta from Ensembl Helpdesk.

Here's the query:

```sql
-- retrieve gene symbols from ensembl
-- inspired by https://www.biostars.org/p/14367/#83094
-- see also https://github.com/cogent3/ensembldb3/issues/7
SELECT
  stable_id AS ensembl_gene_id,
  display_label AS gene_symbol,
  external_db.db_name AS gene_symbol_source_db,
  dbprimary_acc AS gene_symbol_source
FROM gene
LEFT JOIN xref ON xref.xref_id = gene.display_xref_id
LEFT JOIN external_db ON xref.external_db_id = external_db.external_db_id
ORDER BY stable_id
```

Produces output like:


ensembl_gene_id | gene_symbol | gene_symbol_source_db | gene_symbol_source
-- | -- | -- | --
ENSG00000000003 | TSPAN6 | HGNC | HGNC:11858
ENSG00000000005 | TNMD | HGNC | HGNC:17757
ENSG00000000419 | DPM1 | HGNC | HGNC:3005
ENSG00000083622 | AC000061.1 | Clone_based_ensembl_gene | AC000061.1
ENSG00000093100 | AC016026.1 | Clone_based_ensembl_gene | AC016026.1
ENSG00000100101 | Z83844.1 | Clone_based_ensembl_gene | Z83844.1
ENSG00000177340 | FLJ13224 | EntrezGene | 79857
ENSG00000177369 | FLJ40194 | EntrezGene | 124871
ENSG00000179743 | FLJ37453 | EntrezGene | 729614
ENSG00000195401 | Y_RNA | RFAM | RF00019
ENSG00000196274 | Metazoa_SRP | RFAM | RF00017
ENSG00000197334 | Metazoa_SRP | RFAM | RF00017
ENSG00000266919 | hsa-mir-423 | miRBase | MI0001445
ENSG00000272920 | hsa-mir-1253 | miRBase | MI0006387

And to confirm it retrieves a symbol for the gene mentioned above:

ensembl_gene_id | gene_symbol | gene_symbol_source_db | gene_symbol_source
-- | -- | -- | --
ENSG00000170152 | AL391987.1 | Clone_based_ensembl_gene | AL391987.1

In summary, it looks like for each gene, Ensembl picks a single external database to supply the symbol. For `homo_sapiens_core_102_38`, the following external databases contribute these numbers of symbols

```
HGNC                        44231
Clone_based_ensembl_gene    22142
RFAM                         1431
EntrezGene                    195
miRBase                         2
```

The key insight is that the `gene.display_xref_id`, [documented](https://useast.ensembl.org/info/docs/api/core/core_schema.html#gene) as "External reference for EnsEMBL web site. Foreign key references to the xref table.", should be used to lookup the display_label/display_name. And that Ensembl uses display_label/display_name like a gene symbol, although I haven't seen them use the term "symbol".

Does this approach match how ensembldb3 sets the symbol for a gene? If so, thanks for taking a look and feel free to close.

**Comment by GavinHuttley** [comment]
@dhimmel sorry for slow answer.

If you look in the `ensembldb3` source code for [get_genes_matching](https://github.com/cogent3/ensembldb3/blob/894fcc0f13ed3bd250a04d206d37197d58f67d01/ensembldb3/genome.py#L303) there are some comments that point to which tables different values come from, which I reproduce here
```python
        # biotype -> gene
        # description -> gene
        # Symbols -> xref
        # stableid -> gene_stable_id
        # XREF table calls
        # for gene symbols, these need to be matched against the display_label
        # attribute of core.xref table
        # for description, these need to be matched against the description
        # field of the xref table
```

The actual call is made using `Genome._get_gene_query()` which in turn calls `Genome._build_gene_query()`. Because we grab multiple attributes, that's a complex query. Of possible further interest is the method `Genome._get_symbol_from_synonym()` which seeks synonyms for a user input symbol.

If you haven't already, I encourage you to check how all this works by stepping through code execution using an IDE like VS Code, PyCharm, WingIDE etc...

**NOTE:** I have not tested `ensembldb3` against the latest release of Ensembl so I cannot guarantee it will work on that yet. I'm just swamped at the moment and am not sure when I'll get to it.

**Comment by dhimmel** [comment]
Okay, from a glance, I imagine the symbol is getting added in this snippet from `Genome._build_gene_query()`:

https://github.com/cogent3/ensembldb3/blob/894fcc0f13ed3bd250a04d206d37197d58f67d01/ensembldb3/genome.py#L210-L215

This looks to be using the `gene.display_xref_id` table column.

Also of interest to readers might be the [opentargets SQL query](https://github.com/opentargets/platform-input-support/blob/662457a9d7a42d52c98fcb6f32a45b8bddb774cd/scripts/ensembl/create_genes_dictionary.py#L46-L78) for ensembl genes.
